### ISSUE TITLE
TASK AC001 - Allineamento verticale di un elemento in un div

### ISSUE THREAD

**Issue by ralzakark** [Movimento5StelleLazio/ParlamentoElettronicoM5S#164]
Creazione di un set di classi CSS per div per allienare verticalmente un elemento. Il parent del set può avere un'altezza variabile.

Qui trovate un'interessante thread sulla questione: http://stackoverflow.com/questions/79461/vertical-alignment-of-elements-in-a-div

**Comment by ralzakark** [comment]
Nel box di registrazione sotto la start page l'ho implementato così:

``` css
.vtable {
        display: table;
        height: 100%;
}

.table-cell {
        display: table-cell;
        vertical-align: middle;
}
```

Sono le classi rispettivamente del box esterno e di quello interno.
